### ISSUE TITLE
Broken link to content monorepo

### ISSUE THREAD

**Issue by glepretre** [Pocket/pocket-monorepo#330]
The README links to "Content monorepo" but this one returns 404. Is content monorepo still a private repository?

https://github.com/Pocket/pocket-monorepo/blob/6347430896efdc6635311f11f45366f7adbcf902/README.md?plain=1#L3

![image](https://github.com/Pocket/pocket-monorepo/assets/5930831/7736a831-e300-489b-88c3-7897028a2591)

**Comment by kschelonka** [comment]
Thank you.  Yes, this repository is owned by another team and is not yet public.
